version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    cooldown:
      default-days: 7
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/cdk"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps): "
    # The version of AWS CDK libraries must match those from @guardian/cdk.
    # We'd never be able to update them here independently, so just ignore them.
    ignore:
      - dependency-name: "aws-cdk"
      - dependency-name: "aws-cdk-lib"
      - dependency-name: "constructs"
    labels:
      - "dependencies"
    cooldown:
      default-days: 7
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "sbt"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    # Possibly not yet supported for sbt
    # cooldown:
    #   default-days: 7
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
