version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/cdk"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps): "
    ignore:
      # The version of AWS CDK libraries must match those from @guardian/cdk.
      # We'd never be able to update them here independently, so just ignore them.
      - dependency-name: "aws-cdk"
      - dependency-name: "aws-cdk-lib"
      - dependency-name: "constructs"
      # The version of typescript must match the versions required by @guardian/eslint-config-typescript which
      # currently only allows patch updates, so ignore the minor and major version bumps.
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      # The version of eslint must match the versions required by @guardian/eslint-config-typescript which
      # currently only allows patch and minor updates, so ignore the major version bumps.
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

    labels:
      - "dependencies"
    groups:
      all:
        patterns: ["*"]
