AWSTemplateFormatVersion: 2010-09-09
Description: Open and closed security groups for testing

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the VPC SGs will be created in

Resources:
  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Sample open security group for https - bad
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Stack
        Value: security

  ClosedSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Sample closed security group for https - good
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 10.0.0.0/16
      Tags:
      - Key: Stack
        Value: security

