#!/usr/bin/env bash

set -e

(
    cd cdk
    ./script/ci
)

./sbt --no-conf '; project hq; clean; compile; test; Debian / packageBin'

mkdir -p dist
mv hq/target/security-hq_*_all.deb "dist/security-hq-$BUILD_NUMBER.deb"

# Build the cloudwatch-metrics Lambda assembly jar
./sbt --no-conf '; project cloudwatchMetrics; test; assembly'

mkdir -p cloudwatch-metrics-dist
cp cloudwatch-metrics/target/scala-*/cloudwatch-metrics.jar cloudwatch-metrics-dist/cloudwatch-metrics.jar
