#!/usr/bin/env bash

set -e

(
    cd cdk
    ./script/ci
)

./sbt --no-conf '; project hq; clean; compile; test; Debian / packageBin'

# `sbt Debian / packageBin` produces `hq/target/security-hq_x.x.x_all.deb`. Rename it to something easier.
# TODO Work out how to do this within build.sbt
mv hq/target/security-hq_*_all.deb hq/target/security-hq.deb
