#!/usr/bin/env bash
# Creates the directory where DynamoDbLocal will store its state as a file
# Creates a table with the the right schema

mkdir -p ~/.gu/security-hq

aws dynamodb create-table --table-name security-hq-iam-DEV \
    --attribute-definitions AttributeName=id,AttributeType=S AttributeName=dateNotificationSent,AttributeType=N \
    --key-schema AttributeName=id,KeyType=HASH AttributeName=dateNotificationSent,KeyType=RANGE \
    --billing-mode PAY_PER_REQUEST \
    --endpoint-url http://localhost:8000 \
    --region eu-west-1 \
    --profile security
