package com.gu.guardianduty

import io.circe.parser

class GuardDutyEventBridgeEventTest extends munit.FunSuite with TestHelpers {
  test("GuardDutyEventBridgeEvent can be decoded from JSON") {
    val json = {
      """{
        |  "version": "0",
        |  "id": "test-id",
        |  "detail-type": "GuardDuty Finding",
        |  "source": "aws.guardduty",
        |  "account": "111122223333",
        |  "time": "2024-01-01T00:00:00Z",
        |  "region": "eu-west-1",
        |  "detail": {
        |    "id": "abc123findingid",
        |    "accountId": "111122223333",
        |    "severity": 8.5,
        |    "region": "eu-west-1",
        |    "type": "UnauthorizedAccess:EC2/SSHBruteForce",
        |    "title": "SSH brute force attack detected",
        |    "description": "An EC2 instance is under SSH brute force attack."
        |  }
        |}
        |""".stripMargin
    }

    val event = parser
      .decode[GuardDutyEventBridgeEvent](json)
      .rightValue()
    assertEquals(event.id, "test-id")
    assertEquals(event.detail.accountId, "111122223333")
    assertEquals(event.detail.severity, 8.5)
    assertEquals(event.detail.`type`, "UnauthorizedAccess:EC2/SSHBruteForce")
  }

  test("parses a sample event generated by GuardDuty") {
    val json = scala.io.Source
      .fromResource("test-events/sample-guardduty-event.json")
      .mkString

    val event = parser
      .decode[GuardDutyEventBridgeEvent](json)
      .rightValue()
    assertEquals(event.id, "ee33b3c3-9ff9-0d12-f345-6789e56e4321")
    assertEquals(event.detail.id, "dc7f7821c5404f68ad2aa6ff85237ddd")
    assertEquals(event.detail.accountId, "100000000000")
    assertEquals(event.detail.severity, 8.0)
    assertEquals(event.detail.`type`, "Exfiltration:S3/AnomalousBehavior")
    assertEquals(
      event.detail.consoleUrl,
      "https://eu-west-1.console.aws.amazon.com/guardduty/home?region=eu-west-1#/findings?fId=dc7f7821c5404f68ad2aa6ff85237ddd"
    )
  }
}
