package com.gu.guardianduty

import com.gu.anghammarad.models.Notification

import java.time.LocalDate
import scala.concurrent.Future

class GuardianDutySpec extends munit.FunSuite {

  class RecordingNotifications extends Notifications {
    var sent: List[Notification] = Nil
    override def notify(notification: Notification): Future[String] = {
      sent = sent :+ notification
      Future.successful("test-message-id")
    }
  }

  val sampleEvent: String = {
    """{
      |  "version": "0",
      |  "id": "test-id",
      |  "detail-type": "GuardDuty Finding",
      |  "source": "aws.guardduty",
      |  "account": "111122223333",
      |  "time": "2024-01-01T00:00:00Z",
      |  "region": "eu-west-1",
      |  "detail": {
      |    "id": "abc123findingid",
      |    "accountId": "111122223333",
      |    "region": "eu-west-1",
      |    "severity": 8.5,
      |    "type": "UnauthorizedAccess:EC2/SSHBruteForce",
      |    "title": "SSH brute force attack detected",
      |    "description": "An EC2 instance is under SSH brute force attack."
      |  }
      |}
      |""".stripMargin
  }

  val runbookUrl = "https://example.com/runbook"

  val today = LocalDate.of(2024, 1, 1)

  test(
    "processEvent sends notification for an example high severity findings"
  ) {
    val notifications = RecordingNotifications()
    val deps =
      Services(notifications = notifications, logger = new NoOpLogger)

    GuardianDuty.processEvent(sampleEvent, deps, today, runbookUrl)

    assertEquals(notifications.sent.length, 1)
    assert(notifications.sent.head.subject.contains("[HIGH]"))
    assertEquals(
      notifications.sent.head.actions.find(_.cta == "Open runbook").map(_.url),
      Some(runbookUrl)
    )
    assertEquals(
      notifications.sent.head.threadKey,
      Some("abc123findingid-2024-01-01")
    )
  }

  test("processEvent does not notify for an example low severity findings") {
    val lowSeverityEvent =
      sampleEvent.replace("\"severity\": 8.5", "\"severity\": 3.0")
    val notifications = RecordingNotifications()
    val deps =
      Services(notifications = notifications, logger = new NoOpLogger)

    GuardianDuty.processEvent(lowSeverityEvent, deps, today, runbookUrl)

    assertEquals(notifications.sent.length, 0)
  }

  test(
    "processEvent sends notification for a sample finding generated by GuardDuty"
  ) {
    val realEvent: String = {
      scala.io.Source
        .fromResource("test-events/sample-guardduty-event.json")
        .mkString
    }
    val notifications = RecordingNotifications()
    val deps =
      Services(notifications = notifications, logger = new NoOpLogger)

    GuardianDuty.processEvent(realEvent, deps, today, runbookUrl)

    assertEquals(notifications.sent.length, 1)
    assertEquals(
      notifications.sent.head.subject,
      "[HIGH] GuardDuty: Exfiltration:S3/AnomalousBehavior"
    )
    assertEquals(
      notifications.sent.head.threadKey,
      Some("dc7f7821c5404f68ad2aa6ff85237ddd-2024-01-01")
    )
  }
}
