name: Update Dependency Graph for sbt
on:
  push:
    branches:
      - main
      - sbt-dependency-graph-4b85b517403e3b56
  workflow_dispatch: 
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Java
        id: java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: corretto
          java-version: 17
      - name: Install sbt
        id: sbt
        uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8
      - name: Submit dependencies
        id: submit
        uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
      - name: Log snapshot for user validation
        id: validate
        run: cat ${{ steps.submit.outputs.snapshot-json-path }} | jq
    permissions:
      contents: write
