name: Update Dependency Graph for sbt
on:
  push:
    branches:
      - main
      - sbt-dependency-graph-4b85b517403e3b56
  workflow_dispatch: 
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Java
        id: java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.2.0
        with:
          distribution: corretto
          java-version: 17
      - name: Install sbt
        id: sbt
        uses: sbt/setup-sbt@4d1c55d37e6b6207c2952be12394058d9b6e4aa1 # v1.1.3
      - name: Submit dependencies
        id: submit
        uses: scalacenter/sbt-dependency-submission@64084844d2b0a9b6c3765f33acde2fbe3f5ae7d3 # v3.1.0
      - name: Log snapshot for user validation
        id: validate
        run: cat ${{ steps.submit.outputs.snapshot-json-path }} | jq
    permissions:
      contents: write
