name: Snyk IAC

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  GuCdkScan:
    uses: guardian/.github/.github/workflows/pr-gucdk-snyk.yml@nt/iac-scan
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
